baseURL = 'https://Page.github.io/'
languageCode = 'en-us'
theme = 'anatole'
enableEmoji = true

[params]
title = 'My Simple Page'
author = 'Ketsoke'
description = 'A simple blog website in github written by Subin'
profilePicture = "images/profile_pic.jpg"
mainSections = ["blog"]
twitter_cards = true # Enable twitter cards if true
images = ["img/TwitterCard.png"] # Twitter card png
